### PR TITLE
Treat `""` As Missing Value

### PR DESCRIPTION
**Pull request by BeeeQueue**
This PR adds an option to treat `""` values the same as `undefined`.

We use dotenv files to show what options are available in our projects, with empty values in them to show that they are optional or not possible to commit to repositories:

```ini
PORT=8080
APP_ENV=development

SYSTEM_TOKEN=
CDN_URL=
GRAPHQL_URL=
```

```ts
// Current: Errors due to "" not being a valid port
url({
  input: process.env.CDN_URL, // ""
  devDefault: "https://...",
  default: "http://localhost:3000/cdn",
})
// New: Empty string is treated as null, falls back to defaults
```

This causes problems with envsafe when we have default values for these env vars (e.g. defaulting the URLs to `localhost`) since it results in `process.env.CDN_URL = ""`.

- [x] Test manually in project
- [x] Add functionality
- [x] Add tests
- [x] ~~Ensure other validators other than `str()` don't have the `allowEmpty`-property~~
- [x] Update `README.md`

### CODE REVIEW

**Comment by KATT** [comment]
Hey Adam, thanks so much for the PR!

I really like the idea, I actually think it **should be the default behaviour** and an opt-_out_ rather than an opt-_in_ (breaking behaviour so I'll do a new major).

Would you mind updating your PR so the API is something like this? 👇 

Other ideas on approaching the problem are welcome as well.. Also, tick the "Allow edits"-thingy, please :)
### Default behaviour
```ts
import { str, envsafe, port, url } from 'envsafe';

export const env = envsafe({
  CDN_URL: str({
    devDefault: 'http://localhost:3000',
  }),
 // ...
})
```
**❌  Fail** if CDN_URL is empty string

### New option `allowEmpty: boolean` 

- **Only on `str()`** as the other ones are never gonna be valid as empty str

```ts
import { str, envsafe, port, url } from 'envsafe';

export const env = envsafe({
  CDN_URL: str({
    devDefault: 'http://localhost:3000',
    allowEmpty: true,
  }),
 // ...
})
```
**✅  Succeed** if CDN_URL is empty string


### Checklist

- [ ] Add functionality
- [ ] Add tests
- [ ] Ensure other validators other than `str()` don't have the `allowEmpty`-property
- [ ] Update `README.md`

**Comment by BeeeQueue** [comment]
Sure I'll update it!

If you mean allow maintainers to edit it is already checked for me...

image

**Comment by KATT** [comment]
Great, looking forward to reviewing it. I've merged `main` so the CI will now run on this branch now. 

Fine if you want to do a separate PR as well!

**Review by KATT — CHANGES_REQUESTED** [review]
See previous comment https://github.com/KATT/envsafe/pull/31#issuecomment-753540866

**Comment by BeeeQueue** [comment]
Looking into it more I realised that the issue exists on the validators that parse the string input - e.g. `port` and `url`. `str` is fine as it thinks `""` is a valid string, and is g2g already.

After considering the different ways to do this I still think the best way to handle it is an option on `envsafe` rather than the validators as we would have to conditionally handle empty string inputs to them in each validator that it might apply to, which will be a mess to maintain. It'll be a lot easier to change an empty string into null

**Comment by KATT** [comment]
Empty string will never be valid on url nor number/port though, will it?

**Comment by BeeeQueue** [comment]
No, but it does allow defaulting over the missing value instead of it just erroring

**Comment by KATT** [comment]
Oh, true! I didn't consider defaults, now I'm with you. 

Maybe an option to `allowEmpty: boolean` on the env options  / all the validators then and throw `MissingEnvError` if it's not `true` and otherwise pass it to the parsers.

I'm still contemplating if it's better to do it granularly on the validators; I reckon it's rare that one would want to do this and it might be useful to do it granularly.

**Comment by KATT** [comment]
So -

- Either in `Spec` https://github.com/KATT/envsafe/blob/f5e632a32ddbd6367872dc92f29eab22cd86cbfd/src/types.ts#L1
- Or in `EnvsafeOpts ` https://github.com/KATT/envsafe/blob/f5e632a32ddbd6367872dc92f29eab22cd86cbfd/src/types.ts#L50

I'm leaning towards `Spec` being nicer...

**Comment by KATT** [comment]
It'll probably leave the codebase cleaner to do it with the options object though, so do that if you want! Sorry for the back-and-forth! :)

**Comment by BeeeQueue** [comment]
I agree that having the option on the validators for more granular control is better, and I did finally realize that I just had to change where the option came from in the implementation for it to work... 
So that's done as well as the documentation.

Should I also add a changelog? Just the simple template from https://keepachangelog.com/en/1.0.0/

**Review by KATT — APPROVED** [review]

**Comment by KATT** [comment]
Simplified a bit in f24df97c6eb035f617715a4b95e34e6163519a2b

Released as `2.0.0` 🚀 

Thanks!

**Pull request merged**
